const express = require('express')
const admin_route = express()
const session = require('express-session')
const config = require('../config/config')
admin_route.use(express.static('public/admin'))
admin_route.use(session({ secret: config.sessionSecret, saveUninitialized: true, resave: false }))
admin_route.use(express.json())
admin_route.use(express.urlencoded({ extended: true }))

admin_route.set('view engine', 'ejs')
admin_route.set('views', './views/admin')

const adminAuth = require('../middileware/adminAuth')
const adminController = require('../controllers/adminController')
const catogoryController = require('../controllers/catogoryController')
const orderController = require('../controllers/orderController')
const couponController = require('../controllers/couponController')
const bannerController = require('../controllers/bannerController')

const upload = require('../config/multer')

admin_route.get('/', adminAuth.isLogout, adminController.loginLoad)
admin_route.post('/', adminController.verifyLogin)
admin_route.get('/home', adminAuth.isLogin, adminController.loadHome)
admin_route.get('/admin/logout', adminController.logout)
admin_route.get('/table', adminAuth.isLogin, adminController.getTable)
admin_route.get('/blockUser', adminAuth.isLogin, adminController.blockUser)
admin_route.get('/unblockUser', adminAuth.isLogin, adminController.unblockUser)
admin_route.get('/table2', adminAuth.isLogin, adminController.getTable2)
admin_route.get('/registration2', adminAuth.isLogin, adminController.getRegistration2)
admin_route.post('/registration2', upload.upload.array('image', 3), adminController.insertProduct)
admin_route.get('/editProduct', adminAuth.isLogin, adminController.editProduct)
admin_route.post('/editProduct', upload.upload.array('image', 3), adminController.updateProducts)
admin_route.get('/catogory', adminAuth.isLogin, catogoryController.getCatogory)
admin_route.get('/addCatogory', adminAuth.isLogin, catogoryController.getaddCatogory)
admin_route.post('/addCatogory', catogoryController.insertCatogory)
admin_route.get('/blockCatogory', adminAuth.isLogin, catogoryController.blockCatogory)
admin_route.get('/unblockCatogory', adminAuth.isLogin, catogoryController.unblockCatogory)
admin_route.get('/orders', adminAuth.isLogin, orderController.displayordertableload)
admin_route.get('/viewProduct', adminAuth.isLogin, adminController.viewproductload)
admin_route.get('/getcoupon', adminAuth.isLogin, couponController.loadcoupon)
admin_route.get('/addcoupon', adminAuth.isLogin, couponController.loadaddcoupon)
admin_route.get('/editcoupon', adminAuth.isLogin, couponController.loadeditcoupon)
admin_route.post('/addcoupon', couponController.savecoupondetails)
admin_route.post('/editcoupon', couponController.saveeditcoupon)
admin_route.get('/blockcoupon', adminAuth.isLogin, couponController.loadblockcoupon)
admin_route.get('/unblockcoupon', adminAuth.isLogin, couponController.loadunblockcoupon)
admin_route.get('/getsalesreport', adminAuth.isLogin, orderController.loadsalesreport)
// admin_route.get('/exportreport', adminAuth.isLogin, orderController.loadreportpdf)
admin_route.get('/export2report', adminAuth.isLogin, orderController.loadreportexel)
admin_route.get('/delivery', adminAuth.isLogin, orderController.loaddeliverd)
admin_route.post('/delete_images', adminController.deleatephoto)
admin_route.get('/banner', bannerController.loadbanner)
admin_route.get('/addbanner', adminAuth.isLogin, bannerController.loadaddbanner)
admin_route.post('/addbanner', upload.upload.array('image', 3), bannerController.postbanner)
admin_route.get('/removebanner', adminAuth.isLogin, bannerController.loadremovebanner)
admin_route.get('*', function (req, res) {
  res.redirect('/admin')
})

module.exports = admin_route